-- -----------------------------------------------------------------------------
-- BIZU PRO - Database Schema for Render (PostgreSQL)
-- Generated by Antigravity
-- -----------------------------------------------------------------------------

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL DEFAULT 'Estudante',
    email VARCHAR(255) UNIQUE,
    password_hash VARCHAR(255),
    lives INT DEFAULT 5,
    max_lives INT DEFAULT 5,
    streak INT DEFAULT 0,
    xp INT DEFAULT 0,
    level INT DEFAULT 1,
    gems INT DEFAULT 0, -- Virtual currency
    last_login TIMESTAMP,
    last_life_lost TIMESTAMP, -- For lives regeneration
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_premium BOOLEAN DEFAULT FALSE,
    -- Hearts/Lives Persistence
    hearts INT DEFAULT 500, -- User called it 'hearts', mapping to lives logic
    hearts_max INT DEFAULT 500,
    regen_amount INT DEFAULT 500,
    regen_interval_seconds INT DEFAULT 172800, -- 48 hours
    next_hearts_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() + INTERVAL '48 hours',
    last_hearts_claim_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    -- Gamification Persistence
    last_activity_date DATE, -- For daily streak calculation
    best_streak INT DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()

-- 2. COURSES (Concursos)
CREATE TABLE IF NOT EXISTS courses (
    id VARCHAR(50) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    category VARCHAR(50),
    total_modules INT DEFAULT 0,
    total_quizzes INT DEFAULT 0,
    tags JSONB -- PostgreSQL uses JSONB for better performance
);

-- 3. SUBJECTS (Topics)
CREATE TABLE IF NOT EXISTS subjects (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- 4. QUESTIONS (Bank)
CREATE TABLE IF NOT EXISTS questions (
    id SERIAL PRIMARY KEY,
    subject_id VARCHAR(50),
    question_text TEXT NOT NULL,
    explanation TEXT,
    difficulty VARCHAR(20) DEFAULT 'medium', -- Postgres enums are stricter, using varchar for simplicity
    FOREIGN KEY (subject_id) REFERENCES subjects(id)
);

-- 5. QUESTION OPTIONS
CREATE TABLE IF NOT EXISTS question_options (
    id SERIAL PRIMARY KEY,
    question_id INT,
    option_text VARCHAR(255) NOT NULL,
    is_correct BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

-- 6. LESSONS (Guided Mode)
CREATE TABLE IF NOT EXISTS lessons (
    id SERIAL PRIMARY KEY,
    subject_id VARCHAR(50),
    title VARCHAR(255),
    content TEXT,
    slide_order INT,
    interaction_json JSONB,
    FOREIGN KEY (subject_id) REFERENCES subjects(id)
);

-- 7. USER PROGRESS & ERROR BANK
CREATE TABLE IF NOT EXISTS user_errors (
    id SERIAL PRIMARY KEY,
    user_id INT,
    question_id INT,
    count INT DEFAULT 1,
    last_error_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (question_id) REFERENCES questions(id)
);

-- 8. COMPLETED QUIZZES
-- Tracks which quizzes the user has finished (for progress bars)
CREATE TABLE IF NOT EXISTS user_completed_quizzes (
    id SERIAL PRIMARY KEY,
    user_id INT,
    quiz_id VARCHAR(100) NOT NULL, -- using string ID to match 'portugues_0_123...'
    completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    UNIQUE(user_id, quiz_id) -- Prevent duplicate entries for same completion
);

-- =============================================================================
-- SEED DATA (INITIAL POPULATION)
-- =============================================================================

-- Seed Subjects
INSERT INTO subjects (id, name) VALUES 
('portugues', 'Português'),
('direito_const', 'Direito Constitucional'),
('direito_adm', 'Direito Administrativo'),
('informatica', 'Informática'),
('bancario', 'Conhecimentos Bancários'),
('matematica', 'Matemática');

-- Seed Courses (Sample from script.js)
INSERT INTO courses (id, title, description, category, total_modules, total_quizzes, tags) VALUES
('camara-2026', 'Câmara dos Deputados', 'Técnico e Analista Legislativo.', 'legislativo', 10, 500, '["Aberto", "Superior", "R$ 26k+"]'),
('caixa-2026', 'Caixa Econômica', 'Técnico Bancário e TI.', 'bancario', 6, 300, '["Aberto", "Médio", "R$ 6k+"]'),
('pf-2026', 'Polícia Federal', 'Agente, Escrivão e Papiloscopista.', 'policial', 12, 600, '["Previsto", "Superior", "R$ 14k+"]'),
('inss-2026', 'INSS', 'Técnico do Seguro Social.', 'admin', 6, 300, '["Previsto", "Médio", "R$ 7k+"]');

-- Seed Sample Questions (Português)
INSERT INTO questions (subject_id, question_text, explanation) VALUES 
('portugues', 'Na frase "O servidor _[VERB]_ o edital", qual a função sintática de "o edital"?', 'O termo "o edital" completa o sentido do verbo transitivo direto sem preposição.'),
('portugues', 'Assinale a palavra escrita corretamente:', 'A palavra "Exceção" grafada com X e Ç vem do latim exceptio.'),
('direito_const', 'Segundo a CF/88, é fundamento da República Federativa do Brasil:', 'Art. 1º: Soberania, Cidadania, Dignidade, Valores do Trabalho, Pluralismo.');

-- Seed Options for Sample Questions (Assuming IDs 1, 2, 3 based on insertion order)
-- Q1: Sintaxe
INSERT INTO question_options (question_id, option_text, is_correct) VALUES 
(1, 'Objeto Direto', TRUE), (1, 'Objeto Indireto', FALSE), (1, 'Sujeito', FALSE), (1, 'Adjunto Adverbial', FALSE);

-- Q2: Ortografia
INSERT INTO question_options (question_id, option_text, is_correct) VALUES 
(2, 'Exceção', TRUE), (2, 'Ecessão', FALSE), (2, 'Esceção', FALSE), (2, 'Ecceção', FALSE);

-- Q3: Constitucional
INSERT INTO question_options (question_id, option_text, is_correct) VALUES 
(3, 'A soberania', TRUE), (3, 'O voto censitário', FALSE), (3, 'A pena de morte', FALSE), (3, 'O intervencionismo', FALSE);

